##### IMPORTS AND FUNCTION DEFINITIONS

In [1]:
import pandas as pd
from pyannote.metrics.diarization import DiarizationErrorRate
from pyannote.core import Segment, Timeline, Annotation
from itertools import product
import os

# Use below only to analyze single speaker diarization
# TARGET_MODEL_SPEAKER = 'speaker_1'
# TARGET_GOLD_SPEAKER = 'SPEAKER_00'

def convert_model_csv_to_rrtm(model_root_folder, csv_filename):
    """
    Convert the diarization model's CSV output to RTTM format for scoring with pyannote diarization error metrics.
    
    Args:
        model_root_folder (str): The root folder where the model's CSV output is located.
        csv_filename (str): The name of the CSV file to convert.
    Returns:
        None: Writes the RTTM file to the same directory as the CSV file in the diarization model's output folder.
    """

    # Handle P5-S8 to trim upto where gold label exists.
    P5_S8_LIMIT = 1719.725

    with open(os.path.join(model_root_folder, csv_filename[:-4]+".rttm"), 'w') as rttm_file:
        df = pd.read_csv(f"{model_root_folder}/{csv_filename}")
        for _, row in df.iterrows():
            # if(row['speaker'] == TARGET_MODEL_SPEAKER):
                begin = float(row['start_time'])
                end = float(row['end_time'])
                speaker = row['speaker']

                # Special handling for p5-s8
                if "p5-s8" in csv_filename:
                    # Ignore segments that start after gold labels end
                    if begin >= P5_S8_LIMIT:
                         continue
                    # Truncate segments that cross the boundary
                    end = min(end, P5_S8_LIMIT)

                # RTTM format: SPEAKER <file> <channel> <begin> <duration> <conf> <speech_type> <speaker_type> <speaker_name>
                duration = end - begin
                if duration <= 0:
                     continue
                rttm_line = f"SPEAKER {begin:.3f} {duration:.3f} <NA> <NA> <NA> {speaker}\n"
                
                rttm_file.write(rttm_line)

def convert_gold_label_txt_to_rrtm(gold_label_root_folder, txt_filename):
    """
    Convert the gold label diarization annotations from a TXT file (from ELAN) to RTTM format for scoring with pyannote diarization error metrics.
    
    Args:
        gold_label_root_folder (str): The root folder where the gold label TXT file is located.
        txt_filename (str): The name of the TXT file to convert.
    Returns:
        None: Writes the RTTM file to the same directory as the TXT file in the gold label annotations folder.
    """

    df = pd.read_csv(os.path.join(gold_label_root_folder, txt_filename), sep='\t')
    # Create RTTM output
    with open(os.path.join(gold_label_root_folder, txt_filename[:-4]+".rttm"), 'w') as rttm_file:
        for idx, row in df.iterrows():
            # if(row['speaker'] == TARGET_GOLD_SPEAKER):
                begin = float(row['speech_start'])
                end = float(row['speech_end'])
                speaker = row['speaker']
                # RTTM format: SPEAKER <file> <channel> <begin> <duration> <conf> <speech_type> <speaker_type> <speaker_name>
                duration = end - begin
                rttm_line = f"SPEAKER {begin:.3f} {duration:.3f} <NA> <NA> <NA> {speaker}\n"
                rttm_file.write(rttm_line)

def load_rttm_to_annotation(path):
    """Load an RTTM file and convert it to a pyannote.core.Annotation object.
    Args:
        path (str): Path to the RTTM file.
    Returns:
        pyannote.core.Annotation: The loaded annotation."""
    ann = Annotation()
    with open(path, 'r') as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if parts[0] != 'SPEAKER':
                continue
            # handle both custom and standard RTTM token positions
            try:
                start = float(parts[1])
                dur = float(parts[2])
                speaker = parts[-1]
            except Exception:
                start = float(parts[3])
                dur = float(parts[4])
                speaker = parts[-1]
            ann[Segment(start, start + dur)] = speaker
    return ann

def der_component_conversion(der_dict):
    """Convert the DER components from a dictionary to a more human-readable format.
    Args:
        der_dict (dict): The dictionary containing DER components.
    Returns:
        dict: A dictionary with human-readable DER components."""
    return {
        'missed_speech_percent': f"{100*der_dict['missed detection']/der_dict['total']:.2f}",
        'false_alarm_percent': f"{100*der_dict['false alarm']/der_dict['total']:.2f}",
        'confusion_percent': f"{100*der_dict['confusion']/der_dict['total']:.2f}",
        "correct_percent": f"{100*der_dict['correct']/der_dict['total']:.2f}",
        "der": f"{100*der_dict['diarization error rate']:.2f}"
    }

##### SPECIFY FILE_ID, VARIANT_TYPES AND RESULT FORMAT

In [2]:
ids = [
    "p5-s8",
    "p5-s10",
    "p7-s8",
    "p7-s16",
    "p9-s3-1",
    "p9-s9",
    "p11-s4",
    "p11-s11",
    "p12-s3",
    "p12-s6",
    "p17-s2",
    "p17-s6",
    "p18-s15",
    "p18-s17",
]

MODEL_TYPES = [ 
    "ClusteringDiarizer",
    "NeuralDiarizer",
]

VAD_MODELS = [
    "vad_marblenet",
    "vad_multilingual_marblenet",
    "vad_telephony_marblenet",
]

EMBEDDING_MODELS = [
    "titanet_large",
    "ecapa_tdnn",
]

AUDIO_TYPES = [
    "raw_audios",
    "denoised_audios",
]

SPEAKER_MODES = [
    "fixed_num-speakers",
    "auto_num-speakers"
]

OVERLAP_MODES = [
    "overlap",
    "no_overlap",
]

# Cartesian product of all possible combinations
all_configs = list(product(
    MODEL_TYPES,
    AUDIO_TYPES,
    SPEAKER_MODES,
    OVERLAP_MODES,
    VAD_MODELS,
    EMBEDDING_MODELS
))

results = {
    "Model Type": [],
    "Audio Type": [],
    "Speaker Mode": [],
    "Overlap Mode": [],
    "VAD": [],
    "Embedding": [],
    "video_id": [], # Corresponds to the file id in other parts of the script
    "DER": [],
    "False Alarm %": [],
    "Missed Speech %": [],
    "Confusion %": [],
    "Correct %": []
}

##### SPECIFY MAPPING FOR CSV FILES (IF CREATED)

In [3]:
#Mapping for the abbreviations, when creating the CSV file names
MODEL_MAP = {
    "ClusteringDiarizer": "C",
    "NeuralDiarizer": "N"
}

VAD_MAP = {
    "vad_marblenet": "MN",
    "vad_multilingual_marblenet": "MMN",
    "vad_telephony_marblenet": "TMN"
}

EMBEDDING_MAP = {
    "titanet_large": "TL",
    "ecapa_tdnn": "ET"
}

AUDIO_MAP = {
    "raw_audios": "RAW",
    "denoised_audios": "DENOISED"
}

SPEAKER_MAP = {
    "fixed_num-speakers": "FIXED",
    "auto_num-speakers": "AUTO"
}

OVERLAP_MAP = {
    "overlap": "OVERLAP",
    "no_overlap": "NO_OVERLAP"
}

##### GENERATE ALL GOLD LABEL RTTMS AT ONCE

In [4]:
# Path to Reference (Gold Labels) folder
ref_root = "gold_label_diarization_annotations"

# print("Generating gold RTTMs...")

for file_id in ids:

    ref_file_name = f"{file_id}_gold_labels"

    convert_gold_label_txt_to_rrtm(
        ref_root,
        ref_file_name + ".txt"
    )

# print("Done.")

##### LOOP THROUGH COMBINATIONS

In [5]:
os.makedirs("der_results", exist_ok=True)

# Path to Reference (Gold Labels) folder
ref_root = "gold_label_diarization_annotations"

# Loops thorugh all variants
for (
    model_type,
    audio_type,
    speaker_mode,
    overlap_mode,
    vad_model,
    embedding_model
) in all_configs:
    
    # Current configuation's result format to store in CSV output
    config_results = {
        "video_id": [],
        "DER": [],
        "False Alarm %": [],
        "Missed Speech %": [],
        "Confusion %": [],
        "Correct %": []
    }

    # Path to hypothetical (model) diarization outputs
    hyp_root = os.path.join(
        "outputs", 
        model_type,
        audio_type,
        speaker_mode,
        vad_model,
        embedding_model,
        "pred_rttms"
    )

    # Loop through all the audio samples 
    for file_id in ids:
        
        # Path to the sample's Gold Label (Reference) file
        ref_file_name = f"{file_id}_gold_labels"
        
        # Path to the sample's model output (Hypothesis) file
        if audio_type == "denoised_audios":
            hyp_file_name = f"{file_id}_denoised"
        else:
            hyp_file_name = file_id

        try:

            convert_model_csv_to_rrtm(
                hyp_root,
                hyp_file_name + ".csv"
            )

            ref = load_rttm_to_annotation(
                os.path.join(
                    ref_root,
                    ref_file_name + ".rttm"
                )
            )

            hyp = load_rttm_to_annotation(
                os.path.join(
                    hyp_root,
                    hyp_file_name + ".rttm"
                )
            )

            # Decide which overlap mode
            skip_overlap = (overlap_mode == "no_overlap")

            metric = DiarizationErrorRate(
                collar=0.25,
                skip_overlap=skip_overlap
            )

            der = der_component_conversion(
                metric(ref, hyp, detailed=True)
            )

            # Append the current results to the main RESULTS dataframe
            results["video_id"].append(file_id)

            results["Model Type"].append(model_type)
            results["Audio Type"].append(audio_type)
            results["Speaker Mode"].append(speaker_mode)
            results["Overlap Mode"].append(overlap_mode)

            results["VAD"].append(vad_model)
            results["Embedding"].append(embedding_model)

            results["DER"].append(float(der["der"]))
            results["False Alarm %"].append(float(der["false_alarm_percent"]))
            results["Missed Speech %"].append(float(der["missed_speech_percent"]))
            results["Confusion %"].append(float(der["confusion_percent"]))
            results["Correct %"].append(float(der["correct_percent"]))


            # Append the current results to a temporary CONFIG_RESULTS dataframe to store into a seperate CSV file
            config_results["video_id"].append(file_id)
            config_results["DER"].append(float(der["der"]))
            config_results["False Alarm %"].append(float(der["false_alarm_percent"]))
            config_results["Missed Speech %"].append(float(der["missed_speech_percent"]))
            config_results["Confusion %"].append(float(der["confusion_percent"]))
            config_results["Correct %"].append(float(der["correct_percent"]))

        except Exception as e:

            print(
                f"Failed: {model_type},{audio_type},{speaker_mode},{overlap_mode},{vad_model},{embedding_model} | {file_id}"
            )

            print(e)

    config_df = pd.DataFrame(config_results)
    
    # Configure the name of the csv file for current configuration/ model combination 
    csv_name = (
        f"model_{MODEL_MAP[model_type]}"
        f"-vad_{VAD_MAP[vad_model]}"
        f"-embedding_{EMBEDDING_MAP[embedding_model]}"
        f"-audio_{AUDIO_MAP[audio_type]}"
        f"-speaker_{SPEAKER_MAP[speaker_mode]}"
        f"-overlap_{OVERLAP_MAP[overlap_mode]}"
        f"-params_OLD.csv"
    )
    
    # Craete a csv
    config_df.to_csv(
        os.path.join("der_results", csv_name),
        index=False
    )

    print(f"Saved: {csv_name}")

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_TL-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_ET-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_TL-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_ET-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_TL-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_ET-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_TL-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_ET-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_TL-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_ET-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_TL-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_ET-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_TL-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_ET-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_TL-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_ET-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_TL-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_ET-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_TL-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_ET-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_TL-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_ET-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_TL-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_ET-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_MMN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_C-vad_TMN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_TL-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_ET-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_TL-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_ET-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_TL-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_ET-audio_RAW-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_TL-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_ET-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_TL-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_ET-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_TL-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_ET-audio_RAW-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_TL-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_ET-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_TL-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_ET-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_TL-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_ET-audio_RAW-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_TL-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_ET-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_TL-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_ET-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_TL-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_ET-audio_RAW-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_TL-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_ET-audio_DENOISED-speaker_FIXED-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_MMN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_TL-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(
/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

Saved: model_N-vad_TMN-embedding_ET-audio_DENOISED-speaker_AUTO-overlap_NO_OVERLAP-params_OLD.csv

/home/interactionlab/anaconda3/envs/der_env/lib/python3.10/site-packages/pyannote/metrics/utils.py:200: UserWarning: 'uem' was approximated by the union of 'reference' and 'hypothesis' extents.
  warnings.warn(

##### PRINT OUTPUTS

In [6]:
# Print the full results table
df = pd.DataFrame(results)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df

              Model Type       Audio Type        Speaker Mode Overlap Mode  \
0     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
1     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
2     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
3     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
4     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
5     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
6     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
7     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
8     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
9     ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
10    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
11    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
12    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
13    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
14    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
15    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
16    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
17    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
18    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
19    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
20    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
21    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
22    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
23    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
24    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
25    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
26    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
27    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
28    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
29    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
30    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
31    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
32    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
33    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
34    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
35    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
36    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
37    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
38    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
39    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
40    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
41    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
42    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
43    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
44    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
45    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
46    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
47    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
48    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
49    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
50    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
51    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
52    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
53    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
54    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
55    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
56    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
57    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
58    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
59    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
60    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
61    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
62    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
63    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
64    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
65    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
66    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
67    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
68    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
69    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
70    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
71    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
72    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
73    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
74    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
75    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
76    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
77    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
78    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
79    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
80    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
81    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
82    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
83    ClusteringDiarizer       raw_audios  fixed_num-speakers      overlap
84    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
85    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
86    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
87    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
88    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
89    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
90    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
91    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
92    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
93    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
94    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
95    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
96    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
97    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
98    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
99    ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
100   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
101   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
102   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
103   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
104   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
105   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
106   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
107   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
108   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
109   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
110   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
111   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
112   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
113   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
114   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
115   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
116   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
117   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
118   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
119   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
120   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
121   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
122   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
123   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
124   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
125   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
126   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
127   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
128   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
129   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
130   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
131   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
132   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
133   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
134   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
135   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
136   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
137   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
138   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
139   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
140   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
141   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
142   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
143   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
144   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
145   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
146   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
147   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
148   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
149   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
150   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
151   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
152   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
153   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
154   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
155   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
156   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
157   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
158   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
159   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
160   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
161   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
162   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
163   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
164   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
165   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
166   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
167   ClusteringDiarizer       raw_audios  fixed_num-speakers   no_overlap
168   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
169   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
170   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
171   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
172   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
173   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
174   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
175   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
176   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
177   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
178   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
179   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
180   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
181   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
182   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
183   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
184   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
185   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
186   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
187   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
188   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
189   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
190   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
191   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
192   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
193   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
194   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
195   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
196   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
197   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
198   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
199   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
200   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
201   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
202   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
203   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
204   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
205   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
206   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
207   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
208   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
209   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
210   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
211   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
212   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
213   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
214   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
215   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
216   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
217   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
218   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
219   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
220   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
221   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
222   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
223   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
224   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
225   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
226   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
227   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
228   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
229   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
230   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
231   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
232   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
233   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
234   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
235   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
236   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
237   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
238   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
239   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
240   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
241   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
242   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
243   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
244   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
245   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
246   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
247   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
248   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
249   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
250   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
251   ClusteringDiarizer       raw_audios   auto_num-speakers      overlap
252   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
253   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
254   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
255   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
256   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
257   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
258   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
259   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
260   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
261   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
262   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
263   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap
264   ClusteringDiarizer       raw_audios   auto_num-speakers   no_overlap

In [7]:
# df[[
#     "Model Type",
#     "Audio Type",
#     "Speaker Mode",
#     "Overlap Mode",
#     "VAD",
#     "Embedding",
#     "video_id", # Corresponds to the file id in other parts of the script
#     "DER",
#     "False Alarm %",
#     "Missed Speech %",
#     "Confusion %",
#     "Correct %"
# ]]

##### GENERATE SUMMARY OF OUTPUT

In [10]:
summary = (
     df.groupby([
        "Model Type",
        "Audio Type",
        "Speaker Mode",
        "VAD",
        "Embedding",
        "Overlap Mode"
    ])
    .agg({
        "DER": ["mean", "median", "std"],
        "False Alarm %": ["mean", "median", "std"],
        "Missed Speech %": ["mean", "median", "std"],
        "Confusion %": ["mean", "median", "std"],
        "Correct %": ["mean", "median", "std"]
    })
)

# summary = summary.sort_values(
#     ("DER", "median")
# )

summary

                                                                                                                   DER  \
                                                                                                                  mean
Model Type         Audio Type      Speaker Mode       VAD                        Embedding     Overlap Mode
ClusteringDiarizer denoised_audios auto_num-speakers  vad_marblenet              ecapa_tdnn    no_overlap    40.767857
                                                                                               overlap       43.327857
                                                                                 titanet_large no_overlap    42.722857
                                                                                               overlap       44.972143
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    32.743571
                                                                                               overlap       35.435000
                                                                                 titanet_large no_overlap    37.412857
                                                                                               overlap       39.393571
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    41.696429
                                                                                               overlap       43.037143
                                                                                 titanet_large no_overlap    42.990000
                                                                                               overlap       44.040714
                                   fixed_num-speakers vad_marblenet              ecapa_tdnn    no_overlap    45.764286
                                                                                               overlap       47.862143
                                                                                 titanet_large no_overlap    40.837857
                                                                                               overlap       43.419286
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    39.839286
                                                                                               overlap       41.972857
                                                                                 titanet_large no_overlap    36.183571
                                                                                               overlap       38.545714
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    43.170000
                                                                                               overlap       44.689286
                                                                                 titanet_large no_overlap    38.409286
                                                                                               overlap       40.237143
                   raw_audios      auto_num-speakers  vad_marblenet              ecapa_tdnn    no_overlap    54.904286
                                                                                               overlap       57.400714
                                                                                 titanet_large no_overlap    53.055000
                                                                                               overlap       55.527857
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    61.770000
                                                                                               overlap       64.083571
                                                                                 titanet_large no_overlap    60.049286
                                                                                               overlap       62.401429
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    56.860000
                                                                                               overlap       59.515714
                                                                                 titanet_large no_overlap    57.680714
                                                                                               overlap       60.061429
                                   fixed_num-speakers vad_marblenet              ecapa_tdnn    no_overlap    57.417857
                                                                                               overlap       59.695000
                                                                                 titanet_large no_overlap    55.826429
                                                                                               overlap       58.045000
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    66.005714
                                                                                               overlap       67.883571
                                                                                 titanet_large no_overlap    64.690714
                                                                                               overlap       66.611429
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    61.019286
                                                                                               overlap       63.520000
                                                                                 titanet_large no_overlap    58.575714
                                                                                               overlap       61.056429
NeuralDiarizer     denoised_audios auto_num-speakers  vad_marblenet              ecapa_tdnn    no_overlap    52.684286
                                                                                               overlap       52.805000
                                                                                 titanet_large no_overlap    60.265000
                                                                                               overlap       58.977857
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    50.570714
                                                                                               overlap       49.546429
                                                                                 titanet_large no_overlap    73.846429
                                                                                               overlap       69.795000
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    57.892143
                                                                                               overlap       55.588571
                                                                                 titanet_large no_overlap    68.862857
                                                                                               overlap       65.267857
                                   fixed_num-speakers vad_marblenet              ecapa_tdnn    no_overlap    59.553571
                                                                                               overlap       59.052857
                                                                                 titanet_large no_overlap    64.954286
                                                                                               overlap       63.874286
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    56.310714
                                                                                               overlap       55.131429
                                                                                 titanet_large no_overlap    70.334286
                                                                                               overlap       67.324286
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    65.424286
                                                                                               overlap       62.847857
                                                                                 titanet_large no_overlap    72.711429
                                                                                               overlap       69.375000
                   raw_audios      auto_num-speakers  vad_marblenet              ecapa_tdnn    no_overlap    62.002143
                                                                                               overlap       62.987857
                                                                                 titanet_large no_overlap    67.234286
                                                                                               overlap       67.575714
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    66.685000
                                                                                               overlap       67.951429
                                                                                 titanet_large no_overlap    69.654286
                                                                                               overlap       70.671429
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    63.636429
                                                                                               overlap       65.227857
                                                                                 titanet_large no_overlap    70.891429
                                                                                               overlap       71.605000
                                   fixed_num-speakers vad_marblenet              ecapa_tdnn    no_overlap    63.317143
                                                                                               overlap       64.605000
                                                                                 titanet_large no_overlap    66.538571
                                                                                               overlap       67.458571
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    70.227143
                                                                                               overlap       71.654286
                                                                                 titanet_large no_overlap    71.325000
                                                                                               overlap       72.543571
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    68.712857
                                                                                               overlap       70.129286
                                                                                 titanet_large no_overlap    71.135714
                                                                                               overlap       72.067857

                                                                                                                     \
                                                                                                             median
Model Type         Audio Type      Speaker Mode       VAD                        Embedding     Overlap Mode
ClusteringDiarizer denoised_audios auto_num-speakers  vad_marblenet              ecapa_tdnn    no_overlap    35.500
                                                                                               overlap       37.565
                                                                                 titanet_large no_overlap    35.265
                                                                                               overlap       38.775
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    22.600
                                                                                               overlap       28.740
                                                                                 titanet_large no_overlap    28.465
                                                                                               overlap       30.380
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    25.150
                                                                                               overlap       31.150
                                                                                 titanet_large no_overlap    34.320
                                                                                               overlap       36.825
                                   fixed_num-speakers vad_marblenet              ecapa_tdnn    no_overlap    43.910
                                                                                               overlap       47.040
                                                                                 titanet_large no_overlap    36.315
                                                                                               overlap       38.385
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    34.455
                                                                                               overlap       37.950
                                                                                 titanet_large no_overlap    31.855
                                                                                               overlap       35.215
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    41.695
                                                                                               overlap       42.380
                                                                                 titanet_large no_overlap    32.190
                                                                                               overlap       34.975
                   raw_audios      auto_num-speakers  vad_marblenet              ecapa_tdnn    no_overlap    47.290
                                                                                               overlap       48.230
                                                                                 titanet_large no_overlap    42.605
                                                                                               overlap       45.440
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    61.445
                                                                                               overlap       63.550
                                                                                 titanet_large no_overlap    59.535
                                                                                               overlap       62.080
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    55.240
                                                                                               overlap       57.800
                                                                                 titanet_large no_overlap    56.475
                                                                                               overlap       59.220
                                   fixed_num-speakers vad_marblenet              ecapa_tdnn    no_overlap    49.600
                                                                                               overlap       51.055
                                                                                 titanet_large no_overlap    47.850
                                                                                               overlap       50.395
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    67.985
                                                                                               overlap       69.315
                                                                                 titanet_large no_overlap    64.840
                                                                                               overlap       67.035
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    58.135
                                                                                               overlap       58.780
                                                                                 titanet_large no_overlap    56.170
                                                                                               overlap       59.485
NeuralDiarizer     denoised_audios auto_num-speakers  vad_marblenet              ecapa_tdnn    no_overlap    51.430
                                                                                               overlap       53.415
                                                                                 titanet_large no_overlap    57.325
                                                                                               overlap       56.895
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    48.905
                                                                                               overlap       48.740
                                                                                 titanet_large no_overlap    71.805
                                                                                               overlap       66.765
                                                      vad_telephony_marblenet    ecapa_tdnn    no_overlap    47.505
                                                                                               overlap       48.485
                                                                                 titanet_large no_overlap    62.240
                                                                                               overlap       60.590
                                   fixed_num-speakers vad_marblenet              ecapa_tdnn    no_overlap    62.480
                                                                                               overlap       62.090
                                                                                 titanet_large no_overlap    64.140
                                                                                               overlap       63.645
                                                      vad_multilingual_marblenet ecapa_tdnn    no_overlap    51.165
                                                                                               overlap       51.045
                                                                                 titanet_large no_overlap    61.545